#!/usr/bin/env python
# -*- mode:python -*-

from __future__ import print_function, with_statement

import sys
import hashlib
import tempfile
import os
import subprocess
import shlex
import shutil
import itertools
import threading
import time
import collections
import unicodedata

if not type(sys.version_info) is tuple and sys.version_info.major > 2:
    sys.stderr.write('git-fat does not support Python-3 yet.  Please use python2.\n')
    sys.exit(1)

try:
    from subprocess import check_output
    del check_output
except ImportError:
    def backport_check_output(*popenargs, **kwargs):
        r"""Run command with arguments and return its output as a byte string.

        Backported from Python 2.7 as it's implemented as pure python on stdlib.

        >>> check_output(['/usr/bin/python', '--version'])
        Python 2.6.2
        """
        process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
        output, unused_err = process.communicate()
        retcode = process.poll()
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
            error = subprocess.CalledProcessError(retcode, cmd)
            error.output = output
            raise error
        return output
    subprocess.check_output = backport_check_output

BLOCK_SIZE = 4096

def verbose_stderr(*args, **kwargs):
    return print(*args, file=sys.stderr, **kwargs)
def verbose_ignore(*args, **kwargs):
    pass

def mkdir_p(path):
    import errno
    try:
        os.makedirs(path)
    except OSError as exc: # Python >2.5
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else: raise

def umask():
    """Get umask without changing it."""
    old = os.umask(0)
    os.umask(old)
    return old

def readblocks(stream):
    bytes = 0
    while True:
        data = stream.read(BLOCK_SIZE)
        bytes += len(data)
        if not data:
            break
        yield data
def cat_iter(initer, outstream):
    for block in initer:
        outstream.write(block)
def cat(instream, outstream):
    return cat_iter(readblocks(instream), outstream)
def difftreez_reader(input):
    """Incremental reader for git diff-tree -z output

    :oldmode newmode oldsha1 newsha1 modflag\0filename\0:oldmode newmode ...
    """
    buffer = []
    partial = ''
    while True:
        newread = input.read(BLOCK_SIZE)
        if not newread:
            break
        partial += newread
        while True:
            head, sep, partial = partial.partition('\0')
            if not sep:
                partial = head
                break
            buffer.append(head)
            if len(buffer) == 2:
                oldmode, newmode, oldhash, newhash, modflag = buffer[0].split()
                path = buffer[1]
                yield (newhash, modflag, path)
                buffer = []
def gitconfig_get(name, file=None):
    args = ['git', 'config', '--get']
    if file is not None:
        args += ['--file', file]
    args.append(name)
    p = subprocess.Popen(args, stdout=subprocess.PIPE)
    output = p.communicate()[0].strip()
    if p.returncode and file is None:
        return None
    elif p.returncode:
        return gitconfig_get(name)
    else:
        return output
def gitconfig_set(name, value, file=None):
    args = ['git', 'config']
    if file is not None:
        args += ['--file', file]
    args += [name, value]
    p = subprocess.check_call(args)

# Easily connect a list of processes / handlers using pipes, and wait for entire pipe to finish
class Pipe(object):
  Error = RuntimeError

  # Pipe step - launches a process
  class Process(object):
      def __init__(self, command):
          self.command = command.split() if isinstance(command, str) else command
          self.input = self.output = None
      def start(self, isFirst, isLast, input=None):
          stdin = input if input else None if isFirst else subprocess.PIPE
          self.process = subprocess.Popen(self.command, stdin=stdin, stdout=subprocess.PIPE)
          self.input = self.process.stdin
          self.output = self.process.stdout
          return True
      def restart(self, output=None):
          pass
      def wait(self):
          if self.process:
              self.process.wait()

  # Pipe step - converts/filters output of process_1 to input of process_2
  class Handler(object):
      def __init__(self, target, noInput=False):
          self.target = target
          self.noInput = noInput
          if not noInput:
              self.stdin = None
          self.thread = None
      input = property(lambda self : None)
      output = property(lambda self : None)
      def start(self, isFirst, isLast, input=None):
          if self.noInput:
              return False
          elif input:
              self.stdin = input
              return False
          else:
              raise Pipe.Error('Handler must follow a step that produces an output - ' + self.target.__name__)
      def restart(self, output=None):
          if output:
              args = (output) if self.noInput else (self.stdin, output)
              self.thread = threading.Thread(target=self.target, args=args)
              self.thread.start()
          else:
              self.target() if self.noInput else self.target(self.stdin)
      def wait(self):
          if self.thread:
              self.thread.join()

  class Output(object):
      class Buffer(object):
          def __init__(self):
              self.buffer = None
          def write(self, text):
              if not self.buffer:
                  self.buffer = ''
              self.buffer += result
          def close(self):
              pass

      def __init__(self, target):
          self.target = target
          self.stdout = Pipe.Output.Buffer()
      input = property(lambda self : self)
      output = property(lambda self : None)
      def start(self, isFirst, isLast, input=None):
          return False
      def restart(self, output=None):
          if output:
              result = self.stdout.buffer
              if result:
                  output.write(result)
              self.stdout = output
      def wait(self):
          pass
      def write(self, text):
          result = self.target(text)
          if result is not None:
              self.stdout.write(result)
      def close(self):
          self.stdout.close()

  # Pipe
  def __init__(self, steps):
      self.steps = steps
      self.input = self.output = self.notStarted = None
  def append(self, step):
      self.steps.append(step)
      return self
  def start(self, isFirst=True, isLast=True, input=None):
    i = 0
    for step in self.steps:
        stepIsFirst = i == 0
        stepIsLast = i == len(self.steps)-1
        if step.start(stepIsFirst and isFirst, stepIsLast and isLast, self.output):
            if self.notStarted:
                self.notStarted.restart(step.input)
            self.notStarted = None
        else:
            if self.notStarted:
                if step.input:
                    self.notStarted.restart(step.input)
                else:
                    raise Pipe.Error('Invalid steps')
            self.notStarted = step
        if stepIsFirst:
            self.input = step.input
        self.output = step.output
        i += 1
    if self.notStarted and isLast:
        self.notStarted.restart(None)
        self.notStarted = None
    return False if self.notStarted else self  # So can do .start().wait()
  def restart(self, output=None):
      if self.notStarted:
          self.notStarted.restart(output)
  def wait(self):
      for step in self.steps:
          step.wait()

class StatusNoFiles(object):
    def __init__(self, fat, all):
        self.fat = fat
        self.all = all
        self.obj2fat = dict()
        self.obj2file = None
    def filter(self, obj, fname):
        if fname:
            if not self.obj2file:
                self.obj2file = dict()
            self.obj2file[obj] = fname
        return True
    def print_fat_with_filename(self, fat, indent='', obj=None, fname=None):
        suffix = ' "' + fname + '"' if fname else ' obj=' + obj if obj else ' file not found'
        print(indent + fat + suffix)
    def print_fats(self, fathashes, indent='', with_filenames=False):
        if with_filenames:
            if self.obj2file:
                # Have filenames already
                if not self.fat2obj:
                    self.fat2obj = dict([(self.obj2fat[obj], obj) for obj in self.obj2fat])
                for fat in fathashes:
                    obj = self.fat2obj[fat] if fat in self.fat2obj else None
                    filename = self.obj2file[obj] if obj and obj in self.obj2file else None
                    self.print_fat_with_filename(fat, indent, obj, filename)
            else:
                # Lookup filenames
                found = set()
                def print_matches(input):
                    while True:
                        line = input.readline()
                        if not line: # EOF
                            break
                        splits = line.split(None, 1)
                        if len(splits) == 2 and splits[0] in self.obj2fat:
                            fat = self.obj2fat[splits[0]]
                            self.print_fat_with_filename(fat, indent, splits[0], splits[1].rstrip())
                            found.add(fat)
                Pipe([
                    Pipe.Process('git rev-list --objects --all'),
                    Pipe.Handler(print_matches)
                ]).start().wait()

                # Filename not found
                for fat in fathashes:
                    if fat not in found:
                        self.print_fat_with_filename(fat, indent, None, None)
        else:
            # No filenames
            for fat in fathashes:
                print(indent + fat)
    def load_catalog(self):
        self.catalog = self.fat.catalog_objects()
    def handle_referenced(self, line):
        fat, obj = line.split()
        self.obj2fat[obj] = fat
        if self.all:
            filename = self.obj2file[obj] if obj in self.obj2file else None
            self.print_fat_with_filename(fat, '', obj, filename)
    def run(self):
        filter = self.filter if self.all else None
        pipe = self.fat.pipe_referenced_objects(all=self.all, filter=filter).append(Pipe.Output(self.handle_referenced))
        load_catalog = threading.Thread(target=self.load_catalog)
        load_catalog.start()
        pipe.start()
        load_catalog.join()
        pipe.wait()
        referenced = set(self.obj2fat.values())
        orphans = referenced - self.catalog
        garbage = self.catalog - referenced
        if orphans:
            print('Orphan objects:')
            self.print_fats(orphans, '    ', True)
        if garbage:
            print('Garbage objects:')
            self.print_fats(garbage, '    ', False)

class StatusWithFiles(object):
    def __init__(self, fat, files):
        self.fat = fat
        self.paths = set(files)
    def cut_sha1hash(self, input, output):
        # mode obj stage filename \x00 filter \x00 fat
        i = 0
        file = obj = None
        for line in input:
            for part in line.split('\x00'):
                if len(part) == 0:
                    break; # EOF
                if i == 0:
                    mode, obj, stage, file = part.split(None, 3)
                    if mode.startswith('100'):
                        file = file.rstrip()
                    else:
                        file = obj = None
                elif i == 2:
                    if file and (part == 'fat' or not self.fat_files_only):
                        existing = self.obj2file[obj] if obj in self.obj2file else None
                        if existing:
                            if isinstance(existing, list):
                                existing.append(file)
                            else:
                                self.obj2file[obj] = [existing, file]
                        else:
                            self.obj2file[obj] = file
                            output.write(obj + '\n')
                i = (i + 1) % 3
            output.close()
    def handle_referenced(self, line):
        fat, obj = line.split()
        files = self.obj2file[obj]
        if isinstance(files, list):
            for file in files:
                self.did_get_referenced_file(fat, file)
        else:
            self.did_get_referenced_file(fat, files)
    def did_get_referenced_file(self, fat, file):
        self.print_fat('fat', fat, file)
        self.fat_files.add(file)
    def run(self):
        dirs = set()
        files = set()
        for path in self.paths:
            dirs.add(path) if os.path.isdir(path) else files.add(path)
        if len(files) > 0:
            self.run_with_files(files)
        files = None # Free memory
        for dir in dirs:
            self.run_with_files(set(dir), is_dir=True)
    def run_with_files(self, files, is_dir=False): #dir=None):
        self.fat_files = set()
        self.obj2file = dict()
        self.fat_files_only = is_dir
        pipe = self.fat.pipe_filter_referenced_objects(Pipe([
            Pipe.Process(['git','ls-files','-s','-z'] + list(files)),
            Pipe.Process('git check-attr --stdin -z filter'),
            Pipe.Handler(self.cut_sha1hash)
        ])).append(Pipe.Output(self.handle_referenced))
        pipe.start().wait()

        # Not fat
        foundFiles = set([foundFiles for foundFileOrFiles in self.obj2file.values() for foundFiles in (foundFileOrFiles if isinstance(foundFileOrFiles, list) else [foundFileOrFiles])])
        file2obj = dict([
            files2objs for fileOrFiles2obj in ((self.obj2file[obj],obj) for obj in self.obj2file.keys()) for files2objs in (((file,fileOrFiles2obj[1]) for file in fileOrFiles2obj[0]) if isinstance(fileOrFiles2obj[0], list) else [fileOrFiles2obj])
        ])
        unmatched = (foundFiles if is_dir else files) - self.fat_files
        for file in unmatched:
          if file not in foundFiles:
              self.print_error('not a git object', file)
          else:
              filehash = self.fat.file_hash(file)
              if os.path.exists(os.path.join(self.fat.objdir, filehash)):
                  self.print_fat('garbage', filehash, file)
              else:
                  self.print_fat('unmanaged', file2obj[file], file)
    def print_error(self, msg, fname):
        self.print_fat('error', (' ' + msg + ' ').center(40, '-'), fname)
    def print_fat(self, status, hash, fname):
        print('[' + status.center(11) + ']  ' + hash + '  "' + fname + '"')

class GitFat(object):
    DecodeError = RuntimeError
    def __init__(self):
        self.verbose = verbose_stderr if os.environ.get('GIT_FAT_VERBOSE') else verbose_ignore
        try:
            self.gitroot = subprocess.check_output('git rev-parse --show-toplevel'.split()).strip()
        except subprocess.CalledProcessError:
            sys.exit(1)
        self.gitdir = subprocess.check_output('git rev-parse --git-dir'.split()).strip()
        self.objdir = os.path.join(self.gitdir, 'fat', 'objects')
        if os.environ.get('GIT_FAT_VERSION') == '1':
            self.encode = self.encode_v1
        else:
            self.encode = self.encode_v2
        def magiclen(enc):
            return len(enc(hashlib.sha1('dummy').hexdigest(), 5))
        self.magiclen = magiclen(self.encode) # Current version
        self.magiclens = [magiclen(enc) for enc in [self.encode_v1, self.encode_v2]] # All prior versions
    def setup(self):
        mkdir_p(self.objdir)
    def is_init_done(self):
        return gitconfig_get('filter.fat.clean') or gitconfig_get('filter.fat.smudge')
    def is_init_done_v2(self):
        return self.is_init_done() and '%f' in gitconfig_get('filter.fat.clean')
    def assert_init_done(self):
        if not self.is_init_done():
            sys.stderr.write('fatal: git-fat is not yet configured in this repository.\n')
            sys.stderr.write('Run "git fat init" to configure.\n')
            sys.exit(1)
    def get_rsync(self):
        cfgpath   = os.path.join(self.gitroot,'.gitfat')
        remote    = gitconfig_get('rsync.remote', file=cfgpath)
        ssh_port  = gitconfig_get('rsync.sshport', file=cfgpath)
        ssh_user  = gitconfig_get('rsync.sshuser', file=cfgpath)
        options   = gitconfig_get('rsync.options', file=cfgpath)
        if remote is None:
            raise RuntimeError('No rsync.remote in %s' % cfgpath)
        return remote, ssh_port, ssh_user, options
    def get_rsync_command(self,push):
        (remote, ssh_port, ssh_user, options) = self.get_rsync()
        if push:
            self.verbose('Pushing to %s' % (remote))
        else:
            self.verbose('Pulling from %s' % (remote))

        cmd = ['rsync', '--progress', '--ignore-existing', '--from0', '--files-from=-']
        rshopts = ''
        if ssh_user:
            rshopts += ' -l ' + ssh_user
        if ssh_port:
            rshopts += ' -p ' + ssh_port
        if rshopts:
            cmd.append('--rsh=ssh' + rshopts)
        if options:
            cmd += options.split(' ')
        if push:
            cmd += [self.objdir + '/', remote + '/']
        else:
            cmd += [remote + '/', self.objdir + '/']
        return cmd
    def file_hash(self, fname):
        h = hashlib.new('sha1')
        for block in readblocks(open(fname)):
            h.update(block)
        return h.hexdigest()
    def revparse(self, revname):
        return subprocess.check_output(['git', 'rev-parse', revname]).strip()
    def encode_v1(self, digest, bytes):
        'Produce legacy representation of file to be stored in repository.'
        return '#$# git-fat %s\n' % (digest,)
    def encode_v2(self, digest, bytes):
        'Produce representation of file to be stored in repository. 20 characters can hold 64-bit integers.'
        return '#$# git-fat %s %20d\n' % (digest, bytes)
    def decode(self, string, noraise=False):
        cookie = '#$# git-fat '
        if string.startswith(cookie):
            parts = string[len(cookie):].split()
            digest = parts[0]
            bytes = int(parts[1]) if len(parts) > 1 else None
            return digest, bytes
        elif noraise:
            return None, None
        else:
            raise GitFat.DecodeError('Could not decode %s' % (string))
    def decode_stream(self, stream):
        'Return digest if git-fat cache, otherwise return iterator over entire file contents'
        preamble = stream.read(self.magiclen)
        try:
            return self.decode(preamble)
        except GitFat.DecodeError:
            # Not sure if this is the right behavior
            return itertools.chain([preamble], readblocks(stream)), None
    def decode_file(self, fname):
        # Fast check
        try:
            stat = os.lstat(fname)
        except OSError:
            return False, None
        if stat.st_size != self.magiclen:
            return False, None
        # read file
        try:
            digest, bytes = self.decode_stream(open(fname))
        except IOError:
            return False, None
        if isinstance(digest, str):
            return digest, bytes
        else:
            return None, bytes
    def decode_clean(self, body):
        '''
        Attempt to decode version in working tree. The tree version could be changed to have a more
        useful message than the machine-readable copy that goes into the repository. If the tree
        version decodes successfully, it indicates that the fat data is not currently available in
        this repository.
        '''
        digest, bytes = self.decode(body, noraise=True)
        return digest
    def filter_clean(self, instream, outstreamclean, filename=None):
        h = hashlib.new('sha1')
        bytes = 0
        fd, tmpname = tempfile.mkstemp(dir=self.objdir)
        filenameSuffix = ' "%s"' % filename if filename else ''
        try:
            ishanging = False
            cached = False                # changes to True when file is cached
            with os.fdopen(fd, 'w') as cache:
                outstream = cache
                firstblock = True
                for block in readblocks(instream):
                    if firstblock:
                        if len(block) == self.magiclen and self.decode_clean(block[0:self.magiclen]):
                            ishanging = True              # Working tree version is verbatim from repository (not smudged)
                            outstream = outstreamclean
                        firstblock = False
                    h.update(block)
                    bytes += len(block)
                    outstream.write(block)
                outstream.flush()
            digest = h.hexdigest()
            objfile = os.path.join(self.objdir, digest)
            if not ishanging:
                if os.path.exists(objfile):
                    self.verbose('git-fat filter-clean: cache already exists %s%s' % (objfile, filenameSuffix))
                    os.remove(tmpname)
                else:
                    # Set permissions for the new file using the current umask
                    os.chmod(tmpname, int('444', 8) & ~umask())
                    os.rename(tmpname, objfile)
                    self.verbose('git-fat filter-clean: caching to %s%s' % (objfile, filenameSuffix))
                cached = True
                outstreamclean.write(self.encode(digest, bytes))
        finally:
            if not cached:
                os.remove(tmpname)

    def cmd_filter_clean(self, filename=None):
        '''
        The clean filter runs when a file is added to the index. It gets the "smudged" (tree)
        version of the file on stdin and produces the "clean" (repository) version on stdout.
        '''
        try:
            self.setup()
            self.filter_clean(sys.stdin, sys.stdout, filename)
        except:
            e = sys.exc_info()[0]
            verbose_stderr('[git-fat] Error: %s' % e)

    def cmd_filter_smudge(self, filename=None):
        try:
            self.setup()
            result, bytes = self.decode_stream(sys.stdin)
            filenameSuffix = ' "%s"' % filename if filename else ''
            if isinstance(result, str):       # We got a digest
                objfile = os.path.join(self.objdir, result)
                try:
                    cat(open(objfile), sys.stdout)
                    self.verbose('git-fat filter-smudge: restoring from %s%s' % (objfile, filenameSuffix))
                except IOError:                 # file not found
                    self.verbose('git-fat filter-smudge: fat object missing %s%s' % (objfile, filenameSuffix))
                    sys.stdout.write(self.encode(result, bytes))   # could leave a better notice about how to recover this file
            else:                             # We have an iterable over the original input.
                self.verbose('git-fat filter-smudge: not a managed file%s' % filenameSuffix)
                cat_iter(result, sys.stdout)
        except:
            e = sys.exc_info()[0]
            verbose_stderr('[git-fat] Error: %s' % e)
    def catalog_objects(self):
        return set(os.listdir(self.objdir))
    def referenced_objects(self, rev=None, all=False, filter=None):
        referenced = set()
        add_to_referenced = Pipe.Output(lambda line : referenced.add(line.split()[0]))
        pipe = self.pipe_referenced_objects(rev, all, filter).append(add_to_referenced)
        pipe.start().wait()
        return referenced

    def pipe_referenced_objects(self, rev=None, all=False, filter=None):
        if all:
            rev = '--all'
        elif rev is None:
            rev = self.revparse('HEAD')

        def cut_sha1hash(input, output):
            for line in input:
                parts = line.split(None, 1)
                objhash = parts[0]
                fname = parts[1].rstrip() if len(parts) > 1 else None
                if objhash:
                    if not filter or filter(objhash, fname):
                        output.write(objhash + '\n')
            output.close()

        return self.pipe_filter_referenced_objects(Pipe([
            # Revision list gives us object names to inspect with cat-file
            Pipe.Process(['git','rev-list','--objects',rev]),
            # Extract hash
            Pipe.Handler(cut_sha1hash)
        ]))

    def pipe_filter_referenced_objects(self, pipe_objects):
        def filter_gitfat_candidates(input, output):
            for line in input:
                objhash, objtype, size = line.split()
                if objtype == 'blob' and int(size) in self.magiclens:
                    output.write(objhash + '\n')
            output.close()
        def extract_fathashes_from_gitfat_refs(input, output):
            # Process metadata + content format provided by `cat-file --batch`
            while True:
                metadata_line = input.readline()
                if not metadata_line:
                    break  # EOF
                objhash, objtype, size_str = metadata_line.split()
                size, bytes_read = int(size_str), 0
                # We know from filter that item is a candidate git-fat object and
                # is small enough to read into memory and process
                content = ''
                while bytes_read < size:
                    data = input.read(size - bytes_read)
                    if not data:
                        break  # EOF
                    content += data
                    bytes_read += len(data)
                try:
                    fathash = self.decode(content)[0]
                    if output:
                        output.write('' + fathash + ' ' + objhash + '\n')
                except GitFat.DecodeError:
                    self.verbose('decode error: %s' % objhash)
                    pass
                # Consume LF record delimiter in `cat-file --batch` output
                bytes_read = 0
                while bytes_read < 1:
                    data = input.read(1)
                    if not data:
                        break  # EOF
                    bytes_read += len(data)
            if output:
                output.close()

        return Pipe([
            # Provides object hashes to inspect
            pipe_objects,
            # Provides info for git-fat candidates in bulk
            Pipe.Process('git cat-file --batch-check'),
            # Analyse info to identify git-fat candidates
            Pipe.Handler(filter_gitfat_candidates),
            # Provides full contents of identified git-fat candidates in bulk
            Pipe.Process('git cat-file --batch'),
            # Extract fathash from contents
            Pipe.Handler(extract_fathashes_from_gitfat_refs)
        ])

    def orphan_files(self, patterns=[]):
        'generator for all orphan placeholders in the working tree'
        if not patterns or patterns == ['']:
            patterns = ['.']
        for fname in subprocess.check_output(['git', 'ls-files', '-z'] + patterns).split('\x00')[:-1]:
            digest = self.decode_file(fname)[0]
            if digest:
                yield (digest, fname)

    def cmd_status(self, args):
        self.setup()
        if '--all' in args:
            status = StatusNoFiles(fat=self, all=True)
        elif len(args) > 0:
            status = StatusWithFiles(fat=self, files=args)
        else:
            status = StatusNoFiles(fat=self, all=False)
        status.run()

    def is_dirty(self):
        return subprocess.call(['git', 'diff-index', '--quiet', 'HEAD']) == 0
    def cmd_push(self, args):
        'Push anything that I have stored and referenced'
        self.setup()
        # Default to push only those objects referenced by current HEAD
        # (includes history). Finer-grained pushing would be useful.
        pushall = '--all' in args
        files = self.referenced_objects(all=pushall) & self.catalog_objects()
        cmd = self.get_rsync_command(push=True)
        self.verbose('Executing: %s' % ' '.join(cmd))
        p = subprocess.Popen(cmd, stdin=subprocess.PIPE)
        p.communicate(input='\x00'.join(files))
        if p.returncode:
            sys.exit(p.returncode)
    def checkout(self, show_orphans=False):
        'Update any stale files in the present working tree'
        self.assert_init_done()
        for digest, fname in self.orphan_files():
            objpath = os.path.join(self.objdir, digest)
            if os.access(objpath, os.R_OK):
                print('Restoring %s -> %s' % (digest, fname))
                # The output of our smudge filter depends on the existence of
                # the file in .git/fat/objects, but git caches the file stat
                # from the previous time the file was smudged, therefore it
                # won't try to re-smudge. I don't know a git command that
                # specifically invalidates that cache, but changing the mtime
                # on the file will invalidate the cache.
                # Here we set the mtime to mtime + 1. This is an improvement
                # over touching the file as it catches the edgecase where a
                # git-checkout happens within the same second as a git fat
                # checkout.
                stat = os.lstat(fname)
                os.utime(fname, (stat.st_atime, stat.st_mtime + 1))
                # This re-smudge is essentially a copy that restores
                # permissions.
                subprocess.check_call(
                    ['git', 'checkout-index', '--index', '--force', fname])
            elif show_orphans:
                print('Data unavailable: %s %s' % (digest,fname))
    def cmd_pull(self, args):
        'Pull anything that I have referenced, but not stored'
        self.setup()
        refargs = dict()
        if '--all' in args:
            refargs['all'] = True
        for arg in args:
            if arg.startswith('-') or len(arg) != 40:
                continue
            rev = self.revparse(arg)
            if rev:
                refargs['rev'] = rev
        files = self.filter_objects(refargs, self.parse_pull_patterns(args))
        cmd = self.get_rsync_command(push=False)
        self.verbose('Executing: %s' % ' '.join(cmd))
        p = subprocess.Popen(cmd, stdin=subprocess.PIPE)
        p.communicate(input='\x00'.join(files))
        if p.returncode:
            sys.exit(p.returncode)
        self.checkout()

    def parse_pull_patterns(self, args):
        if '--' not in args:
            return ['']
        else:
            idx = args.index('--')
            patterns  = args[idx+1:] #we don't care about '--'
            return patterns

    def filter_objects(self, refargs, patterns):
        files = self.referenced_objects(**refargs) - self.catalog_objects()
        if refargs.get('all'): # Currently ignores patterns; can we efficiently do both?
            return files
        orphans_matched = list(self.orphan_files(patterns))
        orphans_objects = set(map(lambda x: x[0], orphans_matched))
        return files & orphans_objects

    def cmd_checkout(self, args):
        self.checkout(show_orphans=True)

    def cmd_gc(self):
        garbage = self.catalog_objects() - self.referenced_objects()
        print('Unreferenced objects to remove: %d' % len(garbage))
        for obj in garbage:
            fname = os.path.join(self.objdir, obj)
            print('%10d %s' % (os.stat(fname).st_size, obj))
            os.remove(fname)

    def cmd_verify(self):
        """Print details of git-fat objects with incorrect data hash"""
        corrupted_objects = []
        for obj in self.catalog_objects():
            fname = os.path.join(self.objdir, obj)
            data_hash = self.file_hash(fname)
            if obj != data_hash:
                corrupted_objects.append((obj, data_hash))
        if corrupted_objects:
            print('Corrupted objects: %d' % len(corrupted_objects))
            for obj, data_hash in corrupted_objects:
                print('%s data hash is %s' % (obj, data_hash))
            sys.exit(1)

    def cmd_init(self):
        self.setup()
        if self.is_init_done_v2():
            print('Git fat already configured, check configuration in .git/config')
        else:
            gitconfig_set('filter.fat.clean', 'git-fat filter-clean %f')
            gitconfig_set('filter.fat.smudge', 'git-fat filter-smudge %f')
            print('Initialized git fat')
    def gen_large_blobs(self, revs, threshsize):
        """Build dict of all blobs"""
        time0 = time.time()
        def hash_only(input, output):
            """The output of git rev-list --objects shows extra info for blobs, subdirectory trees, and tags.
            This truncates to one hash per line.
            """
            for line in input:
                output.write(line[:40] + '\n')
            output.close()
        revlist = subprocess.Popen(['git', 'rev-list', '--all', '--objects'], stdout=subprocess.PIPE, bufsize=-1)
        objcheck = subprocess.Popen(['git', 'cat-file', '--batch-check'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, bufsize=-1)
        hashonly = threading.Thread(target=hash_only, args=(revlist.stdout, objcheck.stdin))
        hashonly.start()
        numblobs = 0; numlarge = 1
        # Build dict with the sizes of all large blobs
        for line in objcheck.stdout:
            objhash, blob, size = line.split()
            if blob != 'blob':
                continue
            size = int(size)
            numblobs += 1
            if size > threshsize:
                numlarge += 1
                yield objhash, size
        revlist.wait()
        objcheck.wait()
        hashonly.join()
        time1 = time.time()
        self.verbose('%d of %d blobs are >= %d bytes [elapsed %.3fs]' % (numlarge, numblobs, threshsize, time1-time0))
    def cmd_find(self, args):
        maxsize = int(args[0])
        blobsizes = dict(self.gen_large_blobs('--all', maxsize))
        time0 = time.time()
        # Find all names assumed by large blobs (those in blobsizes)
        pathsizes = collections.defaultdict(lambda:set())
        revlist = subprocess.Popen(['git', 'rev-list', '--all'], stdout=subprocess.PIPE, bufsize=-1)
        difftree = subprocess.Popen(['git', 'diff-tree', '--root', '--no-renames', '--no-commit-id', '--diff-filter=AMCR', '-r', '--stdin', '-z'],
                                    stdin=revlist.stdout, stdout=subprocess.PIPE)
        for newblob, modflag, path in difftreez_reader(difftree.stdout):
            bsize = blobsizes.get(newblob)
            if bsize:                     # We care about this blob
                pathsizes[path].add(bsize)
        time1 = time.time()
        self.verbose('Found %d paths in %.3f s' % (len(pathsizes), time1-time0))
        maxlen = max(map(len,pathsizes)) if pathsizes else 0
        for path, sizes in sorted(pathsizes.items(), key=lambda ps: max(ps[1]), reverse=True):
            print('%-*s filter=fat -text # %10d %d' % (maxlen, path,max(sizes),len(sizes)))
        revlist.wait()
        difftree.wait()
    def cmd_index_filter(self, args):
        manage_gitattributes = '--manage-gitattributes' in args
        filelist = set(f.strip() for f in open(args[0]).readlines())
        lsfiles = subprocess.Popen(['git', 'ls-files', '-s'], stdout=subprocess.PIPE)
        updateindex = subprocess.Popen(['git', 'update-index', '--index-info'], stdin=subprocess.PIPE)
        for line in lsfiles.stdout:
            mode, sep, tail = line.partition(' ')
            blobhash, sep, tail = tail.partition(' ')
            stageno, sep, tail = tail.partition('\t')
            filename = tail.strip()
            if filename not in filelist:
                continue
            if mode == "120000":
                # skip symbolic links
                continue
            # This file will contain the hash of the cleaned object
            hashfile = os.path.join(self.gitdir, 'fat', 'index-filter', blobhash)
            try:
                cleanedobj = open(hashfile).read().rstrip()
            except IOError:
                catfile = subprocess.Popen(['git', 'cat-file', 'blob', blobhash], stdout=subprocess.PIPE)
                hashobject = subprocess.Popen(['git', 'hash-object', '-w', '--stdin'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
                def dofilter():
                    self.filter_clean(catfile.stdout, hashobject.stdin, filename)
                    hashobject.stdin.close()
                filterclean = threading.Thread(target=dofilter)
                filterclean.start()
                cleanedobj = hashobject.stdout.read().rstrip()
                catfile.wait()
                hashobject.wait()
                filterclean.join()
                mkdir_p(os.path.dirname(hashfile))
                open(hashfile, 'w').write(cleanedobj + '\n')
            updateindex.stdin.write('%s %s %s\t%s\n' % (mode, cleanedobj, stageno, filename))
        if manage_gitattributes:
            try:
                mode, blobsha1, stageno, filename = subprocess.check_output(['git', 'ls-files', '-s', '.gitattributes']).split()
                gitattributes_lines = subprocess.check_output(['git', 'cat-file', 'blob', blobsha1]).splitlines()
            except ValueError:  # Nothing to unpack, thus no file
                mode, stageno = '100644', '0'
                gitattributes_lines = []
            gitattributes_extra = ['%s filter=fat -text' % line.split()[0] for line in filelist]
            hashobject = subprocess.Popen(['git', 'hash-object', '-w', '--stdin'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
            stdout, stderr = hashobject.communicate('\n'.join(gitattributes_lines + gitattributes_extra) + '\n')
            updateindex.stdin.write('%s %s %s\t%s\n' % (mode, stdout.strip(), stageno, '.gitattributes'))
        updateindex.stdin.close()
        lsfiles.wait()
        updateindex.wait()


if __name__ == '__main__':
    fat = GitFat()
    cmd = sys.argv[1] if len(sys.argv) > 1 else ''
    if cmd == 'filter-clean':
        fat.cmd_filter_clean(sys.argv[2])
    elif cmd == 'filter-smudge':
        fat.cmd_filter_smudge(sys.argv[2])
    elif cmd == 'init':
        fat.cmd_init()
    elif cmd == 'status':
        fat.cmd_status(sys.argv[2:])
    elif cmd == 'push':
        fat.cmd_push(sys.argv[2:])
    elif cmd == 'pull':
        fat.cmd_pull(sys.argv[2:])
    elif cmd == 'gc':
        fat.cmd_gc()
    elif cmd == 'verify':
        fat.cmd_verify()
    elif cmd == 'checkout':
        fat.cmd_checkout(sys.argv[2:])
    elif cmd == 'find':
        fat.cmd_find(sys.argv[2:])
    elif cmd == 'index-filter':
        fat.cmd_index_filter(sys.argv[2:])
    else:
        print('Usage: git fat [init|status|push|pull|gc|verify|checkout|find|index-filter]', file=sys.stderr)
